# Generated by Django 5.0.4 on 2024-04-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
