# Generated by Django 5.0.4 on 2024-04-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0003_appointment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='username',
        ),
    ]
